# Generated by Django 5.2.7 on 2025-02-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_feature_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="implemented_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp for when the feature was implemented.",
                null=True,
            ),
        ),
    ]
