# Generated by Django 5.2.7 on 2025-11-04 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_feature_implemented_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="votes",
            field=models.IntegerField(
                blank=True,
                help_text="Historical vote count captured at implementation time. Only used once the feature is implemented to keep showing votes after nightly cleanup.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vote_records",
                to="main.feature",
            ),
        ),
    ]
