# Generated by Django 5.2.7 on 2025-11-04 10:45

import re

from django.db import migrations, models


def populate_usernames(apps, schema_editor):
    User = apps.get_model("main", "User")
    db_alias = schema_editor.connection.alias

    existing_usernames = set(
        User.objects.using(db_alias)
        .exclude(username__isnull=True)
        .values_list("username", flat=True)
    )

    def normalize(base: str) -> str:
        candidate = re.sub(r"[^a-zA-Z0-9._-]", "", base)
        candidate = candidate.strip("._-")
        return candidate or "user"

    for user in User.objects.using(db_alias).all().order_by("pk"):
        email = (getattr(user, "email", "") or "").strip()
        base = email.split("@", 1)[0] if email else ""
        base = normalize(base)

        candidate = base
        suffix = 1
        while candidate in existing_usernames:
            candidate = f"{base}{suffix}"
            suffix += 1

        user.username = candidate
        user.save(update_fields=["username"])
        existing_usernames.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_feature_votes_alter_vote_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Unique handle members use to sign in and identify themselves.",
                max_length=150,
                null=True,
                blank=True,
            ),
        ),
        migrations.RunPython(populate_usernames, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Unique handle members use to sign in and identify themselves.",
                max_length=150,
                unique=True,
            ),
        ),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
    ]
