# Generated by Django 5.2.7 on 2025-11-08 00:39

from django.db import migrations, models


def populate_implemented_state(apps, schema_editor):
    Feature = apps.get_model("main", "Feature")
    Feature.objects.filter(
        implemented_at__isnull=False, implemented_state__isnull=True
    ).update(implemented_state="successful")


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_feature_expired_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="implemented_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("successful", "Successful"),
                    ("unsuccessful", "Unsuccessful"),
                ],
                help_text="Outcome of the implementation run so we can distinguish successful vs. unsuccessful launches.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.RunPython(
            populate_implemented_state, migrations.RunPython.noop, elidable=True
        ),
    ]
