# Generated by Django 5.2.7 on 2025-11-17 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_feature_missed_vote_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Full quote that may appear in the rotating fortune slot.')),
                ('attribution', models.CharField(help_text='Name or source credited alongside the quote.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when the quote suggestion was created.')),
                ('is_approved', models.BooleanField(default=False, help_text='Indicates whether moderators have cleared this quote for rotation.')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp captured the moment moderation approved the quote.', null=True)),
                ('submitted_by', models.ForeignKey(help_text='Community member who suggested the quote.', on_delete=django.db.models.deletion.CASCADE, related_name='quote_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
