# Generated by Django 5.2.7 on 2025-11-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_feature_implementation_report_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="Short message the member can pin to their profile to share their current focus or vibe.",
                max_length=160,
            ),
        ),
    ]
