# Generated by Django 5.2.7 on 2025-11-21 00:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_user_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="implementation_report_body",
        ),
        migrations.RemoveField(
            model_name="feature",
            name="implementation_report_highlights",
        ),
        migrations.RemoveField(
            model_name="feature",
            name="implementation_report_summary",
        ),
    ]
