# Generated by Django 5.2.7 on 2025-12-01 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_scorerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoreRecord',
        ),
    ]
